---
apiVersion: v1
kind: Secret
metadata:
  name: kdubois-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-lab/kdubois-frontend-gitops
